### ISSUE TITLE
How to work with this in angular platform ?

### ISSUE THREAD

**Issue by offline-pixel** [rndme/aes4js#1]
Hi, 
We are encrypting/decrypting text, jpg, png, pdf using pycrypto[aes-gcm] mode.... however we want to decrypt data on client-side... How we can implement this on our platform ? 

We are using Angular on client-side.

**Comment by rndme** [comment]
I'm not familiar with those packages so I can't offer specific advice, but you're right that interoperability between different platform implementations of the same crypto algos is a challenge. Pay particular attention to the string data format (plain and encrypted and key); is it hex pairs, base64, raw bytes, utf/json/url encoded string, etc. Once you get those input and outputs to match up, you will be able to encrypt on one platform and decrypt on another.
