### ISSUE TITLE
Deterministic salt

### ISSUE THREAD

**Issue by six-two** [rndme/aes4js#3]
Hi, 

thanks a lot for the project, it has been very helpful to understand how crypto can be done in JavaScript.

I am not a cryptographer, but I think it may be suboptimal to use a salt that is deterministically generated from the password. To my understanding it currently is generated like this (in pseudo-code):
```
salt_bytes = Unicode2Bytes(Bytes2Hex(SHA-256("349d" + password + "9d3458694307" + password.length)))
```

This would allow an attacker to pre-calculate the keys for the most common passwords (building a hash table) and then use this to attempt to crack any data encrypted using this library.

My suggestion would be to use a salt that has a random component (or is entirely random), so that if two messages are encrypted the PBKDF2 would use a different salt both times, which would prevent an attacker from performing this kind of attack.

I think it could be easily implemented like this: 
```
salt_bytes = SHA-256("349d" + password + "9d3458694307" + iv)
```

I chose the IV, since it is already known at the time of the key derivation during both en- and decryption and should be entirely random. This would circumvent the need of storing yet another piece of metadata and I think (although again, I am no cryptographer) it should be reasonably secure.

Best regards,
six-two

**Comment by rndme** [comment]
You're right about pre-computation, that's not ideal. To be clear to others users, this doesn't lower computational secrecy, but does permit undesired computation logistics. At 1M+ iterations, that's an expensive rainbow table, but as the project's user count goes up, someone bad might find it worthwhile, so it's getting fixed now while we're young.

The challenge with a fix is not destroying at-rest encryptions by changing the algo. Though it's not huge, the project's usage has picked up lately and I'd hate to lock a non-technical user out of data important enough to protect. I'll probably have to side-car more meta and add a version (the horror) unless I can figure something simpler out. 

Thanks for saying something when you saw something. 

More soon.

**Comment by rndme** [comment]
Alright, I found and rolled out a fix that doesn't break backwards compat. Thanks again!
